name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Build the scout-backend Docker image
      run: |
        docker login ghcr.io -u ${{github.repository_owner}} -p ${{secrets.CR}}
        docker build --target=production . --file Dockerfile --tag ghcr.io/m-valkov/scout-backend:productions
        docker push ghcr.io/m-valkov/scout-backend:productions
