name: Build stage docker image

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Building stage docker image
      run: |
        docker login ghcr.io -u ${{github.repository_owner}} -p ${{ secrets.CR }}
        docker build --target=stage . --file Dockerfile --tag ghcr.io/${{github.repository}}:stage-${{github.sha}}
        docker push ghcr.io/${{github.repository}}:stage-${{github.sha}}
