name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the stage Docker image
      run: docker build --target=stage . --file Dockerfile --tag scout-backend-stage:$(date +%s)
    - name: Build the production Docker image
      run: docker build --target=production . --file Dockerfile --tag scout-backend-stage:$(date +%s)
