name: "Build stage"

# first deploy run with error
# container not found
# all subsequent builds should be stable
on:
  release:
    types: [published]

jobs:
  build:
    name: Build stage image
    runs-on: ubuntu-latest
    if: "github.event.release.prerelease"

    steps:
    - uses: actions/checkout@v2
    
    - name: Building stage docker image
      run: |
        docker login ghcr.io -u ${{github.repository_owner}} -p ${{ secrets.CR }}
        docker build --target=stage . --file Dockerfile --tag ghcr.io/${{github.repository}}:${{github.ref_name}}-stage
        docker push ghcr.io/${{github.repository}}:${{github.ref_name}}-stage
        
  predeploy:
    needs: build
    name: Update images and stop current container
    continue-on-error: true
    runs-on: ubuntu-latest
    steps:
    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.DEPLOY_SSH_IP }}
        username: ${{ secrets.DEPLOY_SSH_USER }}
        key: ${{ secrets.DEPLOY_SSH_KEY }}
        port: ${{ secrets.DEPLOY_SSH_PORT }}
        script: |
          docker pull ghcr.io/${{github.repository}}:${{github.ref_name}}-stage
          docker stop ${{secrets.STAGE_CONTAINER_NAME}}
          docker rm ${{secrets.STAGE_CONTAINER_NAME}}

  deploy:
    needs: predeploy
    name: Deploy stage
    runs-on: ubuntu-latest
    steps:
    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.DEPLOY_SSH_IP }}
        username: ${{ secrets.DEPLOY_SSH_USER }}
        key: ${{ secrets.DEPLOY_SSH_KEY }}
        port: ${{ secrets.DEPLOY_SSH_PORT }}
        script: >
          docker run --name=${{secrets.STAGE_CONTAINER_NAME}}
           -p 3333:80 --restart=always
           -e DOMAIN=${{secrets.DOMAIN}}
           -e SENTRY_DSN=${{secrets.SENTRY_DSN}}
           -e TELEGRAM_BOT_TOKEN=${{secrets.TELEGRAM_BOT_TOKEN}}
           -v ~/logs/scout-stage:/usr/src/app/logs
           -d ghcr.io/${{github.repository}}:${{github.ref_name}}-stage